version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    ports:
      - "8080:8080"     # internal Jenkins UI
      - "50000:50000"   # agent connections
    volumes:
      - jenkins-data:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock # Optional: Mount Docker socket for building images

volumes:
  jenkins-data:

